name: Build Theme

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build CSS theme
        run: npm run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
